version: 0.0
os: linux

files:
  - source: /src
    destination: /home/ec2-user/vycai/proj/

permissions:
  - object: /home/ec2-user/vycai/proj/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /home/ec2-user/vycai/
    pattern: "proj"
    owner: ec2-user
    group: ec2-user
    type:
      - directory

hooks:
  ApplicationStart:
    - location: bin/application_run.sh
      timeout: 120
      runas: ec2-user

